app/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

urlpatterns = [
   path('', views.login_page, name="Login page"),
   path('home/', views.home, name="Home"),
   path('logout/', LogoutView.as_view(next_page='Login page'), name="Logout"),
   path('admin-login/', views.admin_login, name="Admin Login"),
   path('report-form/', views.report_form, name="Report Form"),
   path('dashboard/', views.dashboard, name="Dashboard"),
   path('submit/', views.submit, name="Submit"),
   path('report-submitted/', views.report_submitted, name="Report Submitted"),
   path('mark-addressed/<int:report_id>/', views.mark_addressed, name="Mark Addressed"),
   path('delete/<int:report_id>/', views.delete, name="Delete"),
   path('mark-in-progress/<int:report_id>/', views.mark_in_progress, name="Mark in Progress"),
   path('submit-admin-comment/<int:report_id>/', views.submit_admin_comment, name="Submit Admin Comment"),
   path('sort/', views.sort, name="Sort")
]

reportingsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('app.urls')),
]

app/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.core.mail import send_mail
from django.db.models.signals import post_delete
from django.dispatch import receiver

# Adapted from https://www.pyphilly.org/know-thy-user-custom-user-models-django-allauth/


class ReportSiteUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError("User must include email.")

        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self.db)

        return user
    
    def create_superuser(self, email, password):
        user = self.create_user(email=email, password=password)
        user.is_superuser = True
        user.is_staff = True
        user.is_site_admin = True
        user.save(using=self.db)

        return user

    
class ReportSiteUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(
        verbose_name='Email Address',
        unique=True,
        db_index=True
    )
    username = models.CharField(
        max_length=200,
        blank=True
    )

    full_name = models.CharField(
        max_length=200,
        blank=True
    )
    is_staff = models.BooleanField(default=False)
    is_site_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = "email"

    objects = ReportSiteUserManager()

    def get_full_name(self):
        return self.full_name
    
    def __str__(self):
        return f"{self.email} ({self.full_name})"


def report_file_path(instance, filename):
    if instance.report.user.email == "anonymous@email.com":
        return f'Anonymous_user_report/{filename}'
    else:
        return f'Common_user_report/Report {instance.report.id}/{filename}'


class Report(models.Model):
    user = models.ForeignKey(ReportSiteUser, on_delete=models.CASCADE)
    reportTime = models.DateTimeField()

    class Buildings(models.TextChoices):
        AQC = "1", "Aquatic and Fitness Center"
        AST = "2", "Astronomy Building"
        BRN = "3", "Bryan Hall"
        BRO = "4", "Brown Library"
        CAB = "5", "New Cabell Hall"
        COC = "6", "Cocke Hall"
        CHM = "7", "Chemistry Building"
        CLK = "8", "Clark Hall"
        CLM = "9", "Clemons Library"
        GIL = "10", "Gilmer Hall"
        MCL = "11", "McLeod Hall"
        MEC = "12", "Mechanical Engineering Building"
        MIN = "13", "Minor Hall"
        MON = "14", "Monroe Hall"
        NAU = "15", "Nau Hall"
        NHL = "16", "Newcomb Hall"
        OLS = "17", "Olsson Hall"
        RICE = "18", "Rice Hall"
        RTN = "19", "Rotunda"
        SHA = "20", "Shannon Library"
        THN = "21", "Thornton Hall"
        Other = "22", "Other"  # If choose Other, user will enter the building name, which will replace "Other" in db
    location = models.CharField(max_length=200, choices=Buildings.choices, default=Buildings.AQC)
    
    class EmailStatus(models.TextChoices):
        ReceiveAll = "1", "Receive All"
        ReceiveResolved = "2", "Receive Some"
        ReceiveNone = "3", "Receive None"
    receive_emails = models.CharField(max_length=25, choices=EmailStatus.choices, default=EmailStatus.ReceiveNone)

    class CommonIssue(models.TextChoices):
        NotCommon = "1", "N/A"
        Filter = "2", "Water Fountain Filter"
        BathroomClogged = "3", "Clogging in Bathroom"
        BathroomSupply = "4", "Bathroom Supply"
        ClassEquipment = "5", "Classroom Equipment"
    common_issue = models.CharField(max_length=30, choices=CommonIssue.choices, default=CommonIssue.NotCommon)

    description = models.CharField(max_length=5000)

    class EquipmentStatus(models.TextChoices):
        Functioning = "1", "Functioning"
        Problematic = "2", "Problematic"
        Unusable = "3", "Unusable"
    e_status = models.CharField(max_length=15, choices=EquipmentStatus.choices, default=EquipmentStatus.Functioning)

    files = models.ManyToManyField('SubmittedFiles', related_name='reports', blank=True)

    # Only site admin should be able to change this
    class ReportStatus(models.TextChoices):
        NotAddressed = "1", "Not Addressed"
        InProgress = "2", "In Progress"
        Addressed = "3", "Addressed"
    report_status = models.CharField(max_length=15, choices=ReportStatus.choices, default=ReportStatus.NotAddressed)

    admin_comment = models.CharField(max_length=5000, null=True, blank=True)

    def __str__(self):
        return self.description

    def update_status(self, new_status):
        self.report_status = new_status
        d = {"1": "Not Addressed", "2": "In Progress", "3": "Addressed"}
        if(self.receive_emails == "receive all" or (self.receive_emails == "receive some" and new_status == "3")):
            send_mail(
            "Report Status Update",
            "Your report of an equiptment issue has been updated to " + d[new_status],
            settings.EMAIL_HOST_USER,
            [self.user.email],
            fail_silently=False,
            )
        self.save()

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)

    def add_admin_comment(self, comment):
        self.admin_comment = comment
        self.save()


class SubmittedFiles(models.Model):
    report = models.ForeignKey('Report', on_delete=models.CASCADE)
    file = models.FileField(upload_to=report_file_path, blank=True, null=True)

    def __str__(self):
        return str(self.file)

@receiver(post_delete, sender=SubmittedFiles)
def submitted_files_delete(sender, instance, **kwargs):
    if instance.file:
        instance.file.delete(save=False)

app/templates/app/dashboard.html
{% extends 'components/base.html' %}

{% block content %}
    <div id="adminFlag" data-is-site-admin="{{ user.is_site_admin|yesno:'true,false' }}"></div>

    <script>
    var isSiteAdmin = document.querySelector('#adminFlag').dataset.isSiteAdmin === 'true';

    function viewReportDetails(element, reportID, reportStatus) {
        const detailsDiv = document.getElementById(`report-details-${reportID}`);
        detailsDiv.classList.toggle('d-none');

        // Use AJAX so page doesn't refresh when admin clicks view
        if (reportStatus === "1" && isSiteAdmin) {
            fetch(`/mark-in-progress/${element.getAttribute('data-report-id')}/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': document.querySelector('[name=csrfmiddlewaretoken]').value,
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({'report_status': '2'})
            })
                .then(response => response.json())
        }
    }

    function onFileClick(element) {
        let eId = element.id;
        let embedViewId = `view-${eId}`;

        const embedView = document.getElementById(embedViewId);
        const embedDisabled = embedView.disabled ?? true;

        if (embedDisabled) {
            element.innerText = "Close";
            element.classList.remove("btn-info");
            element.classList.add("btn-danger");

            embedView.classList.remove("d-none");
            embedView.disabled = false;
        } else {
            element.innerText = `View ${eId}`;
            element.classList.remove("btn-danger");
            element.classList.add("btn-info");

            embedView.classList.add("d-none")
            embedView.disabled = true;
        }
    }

    </script>

<body style="background-color:#fefefe">
    <div class="container mt-5">
        <div class="mb-4">
            <h2 class="d-flex justify-content-between align-items-center">
                {% if user.is_site_admin %}
                    All Submitted Reports
                {% else %}
                    Reports submitted by {{ user.username }}
                {% endif %}
                <form action="{% url 'Sort' %}" method="post" name="sort_reports">
                    {% csrf_token %}
                    <select name="Order" class="btn btn-primary" onchange="this.form.submit();">
                        <option value="OldestFirst" {% if order == "OldestFirst" %}selected{% endif %}>Sort by Oldest</option>
                        <option value="NewestFirst" {% if order == "NewestFirst" %}selected{% endif %}>Sort by Newest</option>
                        <option value="ByStatus" {% if order == "ByStatus" %}selected{% endif %}>Sort by Status</option>
                    </select>
                </form>
            </h2>
        </div>
    </div>

        {% if reports.exists %}
            {% for report in reports %}
                <div class="card mb-4">
                    <div class="card-body" style="background: #ebeaea80">
                    <h5 class="card-title">Report #{{ report.id }} - Status: {{ report.get_report_status_display }}</h5>
                    <button onClick="viewReportDetails(this, '{{ report.id }}', '{{ report.report_status }}')" class="btn btn-success mt-2" data-report-id="{{ report.id }}">View Details</button>
                    <div id="report-details-{{ report.id }}" class="report-details d-none align-center mt-3" style="position: relative; padding-bottom: 50px;"> 
                        <div><strong>User:</strong> {{ report.user.username }}</div>
                        <div><strong>Time:</strong> {{ report.reportTime }}</div>
                        <div><strong>Location:</strong> {{ report.location }}</div>
                        <div><strong>Issue:</strong> {{ report.get_common_issue_display }}</div>
                        <div><strong>Description:</strong> {{ report.description }}</div>
                        <div><strong>Equipment Status:</strong> {{ report.get_e_status_display }}</div>
                        <div class="pt-2"><strong>Admin Comment</strong></div>
                        <div style="border: 1px solid #000; padding: 5px; margin-top: 5px; background-color: #f8f8f8;">{{ report.admin_comment }}</div>

                        {% if report.submittedfiles_set.exists %}
                            <div class="pt-2"><strong>Attached Files:</strong></div>
                            {% for file in report.submittedfiles_set.all %}
                                <div class="pt-2 pb-2 mb-4 d-flex flex-column">
                                    <button onclick="onFileClick(this)" class="btn btn-info view-btn" id="{{ file.file.name }}">View {{ file.file.name }}</button>
                                    <embed class="w-100 d-none mt-4" style="height: 32rem" id="view-{{ file.file.name }}" src="{{ file.file.url }}">
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="my-2 mb-4 d-flex">No files attached.</div>
                        {% endif %}

                        {% if user.is_site_admin %}

                            <div class="mb-3">
                                <form action="{% url 'Submit Admin Comment' report.id %}" method="post" name="report_form">
                                {% csrf_token %}
                                    <label for="admin_comment" class="mb-1">Admin Comment</label>
                                    <div class="input-group mb-3">
                                        <input id="admin_comment" type="text" name="admin_comment" class="form-control" style="resize: none;" value="{{ current_description }}">
                                        <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" type="submit">Submit</button>
                                      </div>
                                    </div>

                                </form>
                            </div>

                            <div>
                                <form action="{% url 'Mark Addressed' report.id %}" method="post" class="row g-3 justify-content-center" name="report_form">
                                {% csrf_token %}
                                    <div class="mb-4 d-flex">
                                        <button type="submit" class="btn btn-primary btn-submit">Mark Addressed</button>
                                    </div>
                                </form>
                            </div>
                        {% endif %}

                        <div class="pt-2" style="position: absolute; bottom: 20px; left: 10px;">
                            <form action="{% url 'Delete' report.id %}" method="post" class="row g-3" name="report_form" onsubmit="return confirmDelete();">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger btn-submit">Delete Report</button>
                            </form>
                        </div>
                    </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p>No reports submitted.</p>
        {% endif %}

        <a class="btn btn-primary" href="{% url 'Home' %}">Back to Home</a>
        </div>
    </div>
</body>

<script>
    function confirmDelete() {
        return confirm('Do you want to delete this report?');
    }
</script>
{% endblock %}

app/templates/app/home.html
{% extends 'components/base.html' %}

{% block content %}
<body style="background-color:#fefefe">
    <div class="d-flex w-100 h-100 align-items-center justify-items-center ">
        <div class="m-auto text-center" style="margin-top: -2rem;">
            {% if user.is_site_admin %}
            <div style="margin-top: 200px;">
                <p>Welcome, {{ user.username }} ({{ user.email }}). You are a site admin.</p>
                <p><a href="{% url 'Dashboard' %}" class="btn btn-primary btn-submit mx-1">View All Submitted Reports</a></p>
            </div>
                {% else %}
                {% if user.is_authenticated %}
                <div style="margin-top: 200px;">
                    <p>Welcome, {{ user.username }} ({{ user.email }}).</p>
                    <div class="container pb-2">
                        <a href="{% url 'Dashboard' %}" class="btn btn-primary btn-submit mx-1">View Submitted Reports</a>
                        <a href="{% url 'Report Form' %}" class="btn btn-primary btn-submit mx-1">Submit a Report</a>
                    </div>
                </div>
                {% else %}
                    <div style="margin-top: 200px;">
                        <p>Logged in as Anonymous</p>
                    <a href="{% url 'Report Form' %}" class="btn btn-primary btn-submit mx-1">Submit a Report</a>
                    <div class="pt-2">
                        <a href="/" class="btn btn-primary mx-1">Back to Main Menu</a>
                    </div>

                    </div>
                    
                {% endif %}
            {% endif %}
        </div>
    </div>
</body>
{% endblock %}

app/templates/app/login_page.html
{% extends 'components/base.html' %}

{% load socialaccount %}
{% load static %}
{% block content %}
<body style="background-color:#fefefe">
    <div class="align-items-center d-flex justify-content-center text-center w-100 h-100">
        <div style="margin-top: 2rem;">
            <h1 class="pb-4"><strong>Welcome!</strong></h1>
            <img src="https://api.logo.com/api/v2/images?logo=logo_0c25c701-ccbd-4937-b28b-1c7609a15033&u=1713821966584&format=svg&margins=166&width=1500&height=1000&fit=contain" alt="Site Logo" width="300" height="150">
            <h3 class="pt-4"><strong>About Us</strong></h3>
            <h5 class="pt-2">
                Welcome to EquipmentReporting, a site to report facility and utility issues at UVA. Your reports play a
                crucial role in ensuring a seamless experience for everyone in the UVA community. At EquipmentReporting,
                we believe in transparency and accountability.
            </h5>
            <h5 class="pt-2 pb-2">
                <strong>How to Report</strong>
                <li>
                    <a>Log In: Sign in through Google to submit a report. This allows you to track your report's status.</a>
                </li>
                <li>
                    <a>Anonymous Reporting: Prefer to remain anonymous? No problem. Click on Report Anonymously to get started.</a>
                </li>
            </h5>
            <div class="mt-4">
                <a href="{% provider_login_url 'google' %}?next=/home" class = "btn btn-primary btn-submit mx-1">Log in with Google</a>
                <a href="{% url 'Home' %}" class="btn btn-primary btn-submit mx-1">Report Anonymously</a>
            </div>
        </div>
    </div>
</body>
{% endblock %}

app/templates/app/report_form.html
{% extends 'components/base.html' %}

{% block content %}
<body style="background-color:#fefefe">
    <div class="container">
    <div class="card mt-5">
    <div class="card-body">
        <h4 class="card-title mb-2">Report</h4>
        <h6 class="card-subtitle mb-2 text-muted">Submitting as <span class="fw-bold">{% if user.is_authenticated %}{{ user.username }}{% else %}Anonymous{% endif %}</span></h6>

        <form action="{% url 'Submit' %}" method="post" class="row g-3" enctype="multipart/form-data"
            name="report_form">
           {% csrf_token %}

           <div class="mb-2">
               <label class="mb-1" for="location">Which building is your issue in?</label>
                <select class="form-select" id="location" name="location">
                    <option value="AQC">Aquatic and Fitness Center</option>
                    <option value="AST">Astronomy Building</option>
                    <option value="BRN">Bryan Hall</option>
                    <option value="CAB">New Cabell Hall</option>
                    <option value="COC">Cocke Hall</option>
                    <option value="CHM">Chemistry Building</option>
                    <option value="CLK">Clark Hall</option>
                    <option value="CLM">Clemons Library</option>
                    <option value="GIL">Gilmer Hall</option>
                    <option value="MCL">McLeod Hall</option>
                    <option value="MEC">Mechanical Engineering Building</option>
                    <option value="MIN">Minor Hall</option>
                    <option value="MON">Monroe Hall</option>
                    <option value="NAU">Nau Hall</option>
                    <option value="NHL">Newcomb Hall</option>
                    <option value="OLS">Olsson Hall</option>
                    <option value="RICE">Rice Hall</option>
                    <option value="RTN">Rotunda</option>
                    <option value="SHA">Shannon Library</option>
                    <option value="THN">Thornton Hall</option>
                    <option value="Other">Other</option>
                </select>
           </div>
           <div class="mb-2" id="custom_location" style="display:none;">
               <label class="mb-1" for="custom_location">Please enter the building name: </label>
               <input class="form-control" type="text" name="custom_location">
           </div>
           <div class="mb-2">
               <label class="mb-1" for="common_issue">If you have a common issue, please select it below. Otherwise, select "N/A".</label>
               <select class="form-select" id="common_issue" name="common_issue">
                   <option value="NotCommon">N/A</option>
                   <option value="Filter">Water Fountain Filter</option>
                   <option value="Printer">Printer</option>
                   <option value="BathroomClogged">Clogging in Bathroom</option>
                   <option value="BathroomSupply">Bathroom Supply</option>
                   <option value="ClassEquipment">Classroom Equipment</option>
               </select>
           </div>

            <div class="mb-2">
                <label class="mb-1" for="description">Describe your issue. Please include a floor or room number for this problem.</label>
                <textarea class="form-control" id="description" type="text" name="description" rows="4" cols="50" style="resize: none;" required
                          value="{{ current_description }}"></textarea>
            </div>

           <div class="mb-2">
               <label class="mb-1" for="e_status">What is your issue status?</label>
               <select class="form-select" id="e_status" name="e_status">
                   <option value="Functioning">Functioning</option>
                   <option value="Problematic">Problematic</option>
                   <option value="Unusable">Unusable</option>
               </select>
           </div>
           <div class="mb-2">
               <label for="files" class="form-label">Submit files (.txt, .pdf, .jpg)</label>
               <input class="form-control" id="files" type="file" name="files" accept=".txt, .pdf, .jpg" multiple>
           </div>
           {% if user.is_authenticated %}
            <div class="mb-2">
                <label class="mb-1" for="receive_emails">Would you like to receive email updates?</label>
                <select class="form-select" id="receive_emails" name="receive_emails">
                    <option value="receive none">Do Not Send</option>
                    <option value="receive all">Send After All Updates</option>
                    <option value="receive some">Send Once Resolved</option>
                </select>
            </div>
           {% endif %}
           <div class="d-flex">
               <button type="submit" class="btn btn-primary btn-submit w-100">Submit</button>
           </div>
       </form>
    </div>
    </div>
    </div>
</body>
{% endblock %}

{% block scripts %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
        const locationSelect = document.getElementById('location'); 
        const customLocation = document.getElementById('custom_location');
        
        locationSelect.addEventListener('change', function() {
            customLocation.style.display = this.value === "Other" ? 'block' : 'none';
        });

        const form = document.querySelector('form[name="report_form"]');
        const fileInput = document.getElementById('files');

        form.addEventListener('submit', function(event) {
            const allowed = ['text/plain', 'application/pdf', 'image/jpeg'];
            for (let file = 0; file < fileInput.files.length; file++) {
                if (!allowed.includes(fileInput.files[file].type)) {
                    event.preventDefault();
                    alert('Only .txt, .pdf, and .jpg files are supported');
                }
            }
        });
    });
    </script>

{% endblock scripts %}

app/templates/app/report_submitted.html
{% extends 'components/base.html' %}

{% block content %}
<body style="background-color:#fefefe">
    <div class="pt-3">Report Successfully Submitted!</div>
    <a href="{% url 'Home' %}">Back to Home</a>
</body>
{% endblock %}